.PHONY: clean All

All:
	@echo "----------Building project:[ tic_tac_toe - Debug ]----------"
	@cd "C:\Users\Andrew\Documents\machine_learning\tic_tac_toe" && $(MAKE) -f  "tic_tac_toe.mk"
clean:
	@echo "----------Cleaning project:[ tic_tac_toe - Debug ]----------"
	@cd "C:\Users\Andrew\Documents\machine_learning\tic_tac_toe" && $(MAKE) -f  "tic_tac_toe.mk" clean
